#!/usr/bin/env python3
"""rtkforwardprojections, which the itk-rtk wheel does not ship: the default projector of the C++ tool (Joseph)."""
import argparse
import itk
from itk import RTK as rtk

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--geometry", "-g", required=True)
parser.add_argument("--input", "-i", required=True)
parser.add_argument("--output", "-o", required=True)
rtk.add_rtk3Doutputimage_group(parser)
parser.add_argument("--size", dest="dimension", type=rtk.comma_separated_args(int))
args = parser.parse_args()

ImageType = itk.Image[itk.F, 3]
geometry = rtk.read_geometry(args.geometry)
source = rtk.ConstantImageSource[ImageType].New()
rtk.SetConstantImageSourceFromArgParse(source, args)
size = source.GetSize()
size[2] = len(geometry.GetGantryAngles())  # one projection per angle, as the C++ tool
source.SetSize(size)
projector = rtk.JosephForwardProjectionImageFilter[ImageType, ImageType].New()
projector.SetInput(0, source.GetOutput())
projector.SetInput(1, itk.imread(args.input, itk.F))
projector.SetGeometry(geometry)
itk.imwrite(projector.GetOutput(), args.output)
