#!/usr/bin/env python3
"""Build the Reg. rows (CT-only registration controls) of Table 9.

Per task and region: mean and population std over patients; group rows pool patients
and are left empty when a member region is missing. d_SAM and LPIPS are x100. Dice
uses the label filtering of table_09_registration_dice.py, with the
label sets read from --labels-root (the paper's supervised CV_SEG files by default).
"""

from __future__ import annotations

import os
import argparse
import json
import statistics
from pathlib import Path

import table_09_registration_dice as seg

ROOT = seg.ROOT
OUTPUT_PATH = ROOT / os.environ.get("IMPACTSYNTH_TABLES", "tables/from_metrics") / "table_09_registration_rows.tex"
ROWS = (
    ("AB", ("AB",)),
    ("HN", ("HN",)),
    ("TH", ("TH",)),
    ("AB/HN/TH", ("AB", "HN", "TH")),
    ("Brain/Pelvis", ("brain", "pelvis")),
)
# column, branch, folder suffix, JSON key, scale, decimals
COLUMNS = (
    ("MAE", "Registration_ELX_IMPACT", "", "CT_deformed:CT;MASK:MAE", 1, 2),
    ("PSNR", "Registration_ELX_IMPACT", "", "CT_deformed:CT;MASK:PSNR", 1, 2),
    ("SSIM", "Registration_ELX_IMPACT", "", "CT_deformed:CT;MASK:SSIM", 1, 3),
    ("d_SAM", "Registration_ELX_IMPACT_Perceptual", "1", "CT_deformed:CT:SAM_Perceptual", 100, 3),
    ("LPIPS", "Registration_ELX_IMPACT_Perceptual", "", "CT_deformed:CT:LPIPS", 100, 1),
    ("Dice", "Registration_ELX_IMPACT_SEG", "", None, 1, 3),
)


def patient_values(task: str, region: str, column: tuple, labels_root: Path) -> dict[str, float]:
    _, branch, suffix, key, scale, _ = column
    folder = seg.EVALUATIONS / branch / task / f"{region}{suffix}"
    if key is None:
        path = folder / "Metric_TRAIN.json"
        if not path.is_file():
            return {}
        labels = seg.combined_seg_logic.shared_seg_labels_for_region(
            labels_root / task / "Supervised", region, seg.TASK_CONFIG[task]["min_shared_dice"]
        )
        return seg.patient_means_from_metric(path, labels)
    values: dict[str, float] = {}
    for path in folder.glob("Metric_TRAIN*.json"):  # Task 1 TH/brain LPIPS is in Metric_TRAIN1.json
        values.update(json.loads(path.read_text(encoding="utf-8"))["case"].get(key, {}))
    return {patient: scale * value for patient, value in values.items() if value == value}


def cell(task: str, regions: tuple[str, ...], column: tuple, labels_root: Path) -> str:
    pooled = []
    for region in regions:
        values = patient_values(task, region, column, labels_root)
        if not values:
            return "--"
        pooled.extend(values.values())
    digits = column[5]
    return f"{statistics.fmean(pooled):.{digits}f} \\pm {statistics.pstdev(pooled):.{digits}f}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--labels-root", type=Path, default=ROOT / "results/raw/Evaluations",
                        help="tree holding Task_t/Supervised/IMPACT/CV_SEG for the Dice label sets")
    args = parser.parse_args()

    names = [column[0] for column in COLUMNS]
    lines = [r"% Table 9, Reg. rows; generated by table_09_registration_rows.py",
             "% Task & Region & " + " & ".join(names)]
    for task in ("Task_1", "Task_2"):
        for label, regions in ROWS:
            cells = [cell(task, regions, column, args.labels_root) for column in COLUMNS]
            lines.append(f"{task.replace('_', ' ')} & {label} & " + " & ".join(c if c == "--" else f"${c}$" for c in cells) + r" \\")
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
